### ISSUE TITLE
Support add_asset from Controllers

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-core#13]
Hi @amostajo,

I might simply be _doing_it_wrong but I have a controller which I'm trying to call add_asset from. If I call it from Main.php it works fine but if I call it using the Main class global it silently fails. Is it possible?

Thanks

**Comment by amostajo** [comment]
@garretthyder I believe we will need to refactor `wpmvc-mvc` package to accomplish this. Since the best solution would be to pass "by reference" the main class to the controller.

**Comment by garretthyder** [comment]
Thanks @amostajo would the same go for doing an add_action/add_filter/add_shortcode from the Controllers. In some cases there's some logic such as permissions checks I want to do before doing an add_action or add_filter. Right now I'm doing that in the Main.php but would prefer modulating and containing it inside it's Controller.

**Comment by amostajo** [comment]
@garretthyder Having this `add_` from anywhere breaks a little the idea of having a router file (which is the Main class).

I have been using the framework for multiple projects in the past years and something useful for maintenance has been having all WordPress registrations in one place, this provides order in the structure of the project, standardizes development and helps to do reverse engineering. This also improves development in teams.

For now, I rather have these only available form the Main class.

What we can do, is extend the auto-enqueue and `add_asset()` to allow to:
* **Register only**: Set if the asset should only be registered and not enqueue.
* **Version**: File version if this is external and different from the project version.

This way, inside the controller, instead of calling to `$this->add_asset()` you can use WordPress's `wp_enqueue_script()` on registered assets.

**Comment by garretthyder** [comment]
Thanks for the feedback @amostajo 

That would definitely work out nicely for add_asset allowing the enqueue to occur only if certain conditions are met.

And I'll for now avoid use of the add_filter and add_action, but guess I can resort to WP versions of them if needed. The one case I was doing was the `wp_mail_content_type` filter before and after sending email in order to set the content type to html and then revert.

**Comment by amostajo** [comment]
`add_asset()` should include parameters for $version, $register only and $name. These should also extend to the `auto-enqueue` feature.

**Comment by amostajo** [comment]
Looks like I already had the `$register` setting. Lol.
