### ISSUE TITLE
on_admin vs admin_init

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-core#8]
Hello @amostajo,

I was initially confused by the `on_admin` function and was wondering why it's not `admin_init` to follow the WP naming convention. I see it's registered in the WP `init` hook using `is_admin` and was mostly curious why setup that way instead of through the WP `admin_init` hook?

Thanks

**Comment by amostajo** [comment]
@garretthyder `on_admin()` is triggered on the `plugins_loaded` hook, way before `admin_init`. And helps decrease the number of hooks declared in the site when not in the admin dashboard.

Moving this to `admin_init` is a no-no, because you will not be able to deactivate hooks (`remove_action`) prior to `admin_init`. more so, those with priority 1.

EDITED: Same goes with `init()`, it is loaded during `plugins_loaded` and not the `init` hook.

**Comment by garretthyder** [comment]
Ahh thanks for the information @amostajo that makes alot more sense. Cheers
